package types

// McpClient represents an MCP client that is authorized to access the MCPJungle MCP Proxy server.
type McpClient struct {
	// Name is the name of the client that uniquely identifies it within mcpungle.
	Name        string `json:"name"`
	Description string `json:"description"`
	AccessToken string `json:"access_token,omitempty"`

	// IsCustomAccessToken indicates whether the access token was provided by the user (true) or generated by MCPJungle (false).
	IsCustomAccessToken bool `json:"is_custom_access_token"`

	// AllowList is a list of MCP Servers that this client is allowed to access from MCPJungle.
	AllowList []string `json:"allow_list"`
}

// AllowAllMcpServers is a wildcard operator used to indicate that a mcp client has access to all mcp servers
// in mcpjungle.
const AllowAllMcpServers = "*"
